# Form implementation generated from reading ui file 'waiting_room.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setStyleSheet("#frame {\n"
"    background: qradialgradient(\n"
"        spread:pad, cx:0.5, cy:0.4, radius:0.6, fx:0.5, fy:0.4,\n"
"        stop:0 rgba(180, 0, 0, 255),\n"
"        stop:1 rgba(20, 0, 0, 255)\n"
"    );\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame.setObjectName("frame")
        self.frame_layout = QtWidgets.QVBoxLayout(self.frame)
        self.frame_layout.setContentsMargins(40, 30, 40, 20)
        self.frame_layout.setSpacing(0)
        self.frame_layout.setObjectName("frame_layout")
        self.label_title = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(10)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("color: rgba(255, 200, 180, 120);\n"
"background: transparent;\n"
"letter-spacing: 4px;")
        self.label_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.frame_layout.addWidget(self.label_title)
        spacerItem = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.frame_layout.addItem(spacerItem)
        self.players_row = QtWidgets.QHBoxLayout()
        self.players_row.setSpacing(0)
        self.players_row.setObjectName("players_row")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.players_row.addItem(spacerItem1)
        self.p1_layout = QtWidgets.QVBoxLayout()
        self.p1_layout.setSpacing(12)
        self.p1_layout.setObjectName("p1_layout")
        self.gamer1_icon = QtWidgets.QLabel(parent=self.frame)
        self.gamer1_icon.setMinimumSize(QtCore.QSize(220, 220))
        self.gamer1_icon.setMaximumSize(QtCore.QSize(220, 220))
        self.gamer1_icon.setStyleSheet("border: 2px solid rgba(220, 50, 40, 170);\n"
"border-radius: 6px;\n"
"background-color: rgba(0, 0, 0, 80);")
        self.gamer1_icon.setText("")
        self.gamer1_icon.setScaledContents(True)
        self.gamer1_icon.setObjectName("gamer1_icon")
        self.p1_layout.addWidget(self.gamer1_icon, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.gamer1_name = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        font.setBold(True)
        self.gamer1_name.setFont(font)
        self.gamer1_name.setStyleSheet("color: #ffffff;\n"
"background: transparent;\n"
"letter-spacing: 2px;")
        self.gamer1_name.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.gamer1_name.setObjectName("gamer1_name")
        self.p1_layout.addWidget(self.gamer1_name, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.players_row.addLayout(self.p1_layout)
        spacerItem2 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.players_row.addItem(spacerItem2)
        self.vs_col = QtWidgets.QVBoxLayout()
        self.vs_col.setSpacing(6)
        self.vs_col.setObjectName("vs_col")
        self.vs_line_top = QtWidgets.QFrame(parent=self.frame)
        self.vs_line_top.setMinimumSize(QtCore.QSize(1, 28))
        self.vs_line_top.setMaximumSize(QtCore.QSize(1, 28))
        self.vs_line_top.setStyleSheet("background-color: rgba(220, 50, 40, 100); border: none;")
        self.vs_line_top.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.vs_line_top.setObjectName("vs_line_top")
        self.vs_col.addWidget(self.vs_line_top, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setMinimumSize(QtCore.QSize(70, 0))
        self.label.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(20)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgba(220, 50, 40, 210);\n"
"background: transparent;\n"
"letter-spacing: 3px;")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.vs_col.addWidget(self.label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.vs_line_bot = QtWidgets.QFrame(parent=self.frame)
        self.vs_line_bot.setMinimumSize(QtCore.QSize(1, 28))
        self.vs_line_bot.setMaximumSize(QtCore.QSize(1, 28))
        self.vs_line_bot.setStyleSheet("background-color: rgba(220, 50, 40, 100); border: none;")
        self.vs_line_bot.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.vs_line_bot.setObjectName("vs_line_bot")
        self.vs_col.addWidget(self.vs_line_bot, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.players_row.addLayout(self.vs_col)
        spacerItem3 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.players_row.addItem(spacerItem3)
        self.p2_layout = QtWidgets.QVBoxLayout()
        self.p2_layout.setSpacing(12)
        self.p2_layout.setObjectName("p2_layout")
        self.gamer2_icon = QtWidgets.QLabel(parent=self.frame)
        self.gamer2_icon.setMinimumSize(QtCore.QSize(220, 220))
        self.gamer2_icon.setMaximumSize(QtCore.QSize(220, 220))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(42)
        font.setBold(True)
        self.gamer2_icon.setFont(font)
        self.gamer2_icon.setStyleSheet("border: 2px dashed rgba(220, 50, 40, 100);\n"
"border-radius: 6px;\n"
"background-color: rgba(0, 0, 0, 60);\n"
"color: rgba(220, 50, 40, 100);")
        self.gamer2_icon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.gamer2_icon.setObjectName("gamer2_icon")
        self.p2_layout.addWidget(self.gamer2_icon, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.gamer2_name = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(10)
        self.gamer2_name.setFont(font)
        self.gamer2_name.setStyleSheet("color: rgba(255, 150, 130, 120);\n"
"background: transparent;\n"
"letter-spacing: 1px;")
        self.gamer2_name.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.gamer2_name.setObjectName("gamer2_name")
        self.p2_layout.addWidget(self.gamer2_name, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.players_row.addLayout(self.p2_layout)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.players_row.addItem(spacerItem4)
        self.frame_layout.addLayout(self.players_row)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.frame_layout.addItem(spacerItem5)
        self.label_waiting = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        font.setPointSize(9)
        self.label_waiting.setFont(font)
        self.label_waiting.setStyleSheet("color: rgba(255, 190, 170, 130);\n"
"background: transparent;\n"
"letter-spacing: 3px;")
        self.label_waiting.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_waiting.setObjectName("label_waiting")
        self.frame_layout.addWidget(self.label_waiting)
        spacerItem6 = QtWidgets.QSpacerItem(20, 8, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.frame_layout.addItem(spacerItem6)
        self.progressBar = QtWidgets.QProgressBar(parent=self.frame)
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 5))
        self.progressBar.setStyleSheet("QProgressBar {\n"
"    background-color: rgba(255, 255, 255, 20);\n"
"    border: 1px solid rgba(220, 50, 40, 80);\n"
"    border-radius: 3px;\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: rgba(200, 40, 30, 220);\n"
"    border-radius: 3px;\n"
"}")
        self.progressBar.setMinimum(0)
        self.progressBar.setMaximum(0)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.frame_layout.addWidget(self.progressBar)
        self.gridLayout_3.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Risk"))
        self.label_title.setText(_translate("MainWindow", "OYUNCU BEKLENİYOR"))
        self.gamer1_name.setText(_translate("MainWindow", "TextLabel"))
        self.label.setText(_translate("MainWindow", "VS"))
        self.gamer2_icon.setText(_translate("MainWindow", "?"))
        self.gamer2_name.setText(_translate("MainWindow", "Rakip Aranıyor..."))
        self.label_waiting.setText(_translate("MainWindow", "EŞLEŞME ARANIYOR..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
