# Form implementation generated from reading ui file 'waiting_room.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setStyleSheet("background: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, \n"
"                            stop:0 rgba(180, 0, 0, 255),   \n"
"                            stop:1 rgba(20, 0, 0, 255));    ")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        self.frame_2.setStyleSheet("background-color: rgba(0, 0, 0, 180);      \n"
"border-radius: 20px;                ")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem1, 2, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem3, 0, 1, 1, 1)
        self.frame_3 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_3.setMinimumSize(QtCore.QSize(500, 200))
        self.frame_3.setMaximumSize(QtCore.QSize(150, 200))
        self.frame_3.setStyleSheet("#frame_3{\n"
"    background-color: rgba(0, 0, 0, 0); /* 160 şeffaflık seviyesi */\n"
"    border-radius: 20px;                 /* Köşe yumuşatması */\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_4.setContentsMargins(-1, 12, -1, -1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gamer2_icon = QtWidgets.QLabel(parent=self.frame_3)
        self.gamer2_icon.setObjectName("gamer2_icon")
        self.gridLayout_4.addWidget(self.gamer2_icon, 0, 2, 1, 1)
        self.gamer1_icon = QtWidgets.QLabel(parent=self.frame_3)
        self.gamer1_icon.setMinimumSize(QtCore.QSize(100, 100))
        self.gamer1_icon.setObjectName("gamer1_icon")
        self.gridLayout_4.addWidget(self.gamer1_icon, 0, 0, 1, 1)
        self.gamer1_name = QtWidgets.QLabel(parent=self.frame_3)
        self.gamer1_name.setMaximumSize(QtCore.QSize(16777215, 20))
        self.gamer1_name.setStyleSheet("background-color: rgba(0, 0, 0, 0); /* 160 şeffaflık seviyesi */")
        self.gamer1_name.setObjectName("gamer1_name")
        self.gridLayout_4.addWidget(self.gamer1_name, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgba(0, 0, 0, 0); /* 160 şeffaflık seviyesi */")
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 1, 2, 1)
        self.gamer2_name = QtWidgets.QLabel(parent=self.frame_3)
        self.gamer2_name.setStyleSheet("background-color: rgba(0, 0, 0, 0); /* 160 şeffaflık seviyesi */")
        self.gamer2_name.setObjectName("gamer2_name")
        self.gridLayout_4.addWidget(self.gamer2_name, 1, 2, 1, 1)
        self.gridLayout.addWidget(self.frame_3, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.frame_2, 0, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(parent=self.frame)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_2.addWidget(self.progressBar, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.gamer2_icon.setText(_translate("MainWindow", "TextLabel"))
        self.gamer1_icon.setText(_translate("MainWindow", "TextLabel"))
        self.gamer1_name.setText(_translate("MainWindow", "TextLabel"))
        self.label.setText(_translate("MainWindow", "Oyuncu Bekleniyor..."))
        self.gamer2_name.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
