# Form implementation generated from reading ui file 'game_window.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_GameWindow(object):
    def setupUi(self, GameWindow):
        GameWindow.setObjectName("GameWindow")
        GameWindow.resize(1200, 700)
        GameWindow.setStyleSheet("background-color: #0a1e46;")

        self.centralwidget = QtWidgets.QWidget(parent=GameWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")

        self.mapContainer = QtWidgets.QWidget(parent=self.centralwidget)
        self.mapContainer.setObjectName("mapContainer")

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.mapView.sizePolicy().hasHeightForWidth())
        self.mapView.setSizePolicy(sizePolicy)
        self.mapView.setStyleSheet("border: none; background: transparent;")
        self.mapView.setDragMode(QtWidgets.QGraphicsView.DragMode.ScrollHandDrag)
        self.mapView.setRenderHints(QtGui.QPainter.RenderHint.Antialiasing)
        self.mapView.setObjectName("mapView")
        self.verticalLayout.addWidget(self.mapView)
        GameWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(GameWindow)
        QtCore.QMetaObject.connectSlotsByName(GameWindow)

    def retranslateUi(self, GameWindow):
        _translate = QtCore.QCoreApplication.translate
        GameWindow.setWindowTitle(_translate("GameWindow", "Risk — Dünya Haritası"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GameWindow = QtWidgets.QMainWindow()
    ui = Ui_GameWindow()
    ui.setupUi(GameWindow)
    GameWindow.show()
    sys.exit(app.exec())
