# Form implementation generated from reading ui file 'client/ui/ui_files/end_window.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EndScreen(object):
    def setupUi(self, EndScreen):
        EndScreen.setObjectName("EndScreen")
        EndScreen.resize(900, 600)
        EndScreen.setStyleSheet("\n"
"QWidget#EndScreen {\n"
"    background-color: #0d0000;\n"
"}\n"
"\n"
"QLabel#titleLabel {\n"
"    color: #cc1111;\n"
"    font-family: \"Georgia\", serif;\n"
"    font-size: 13px;\n"
"    letter-spacing: 8px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel#resultLabel {\n"
"    font-family: \"Georgia\", serif;\n"
"    font-size: 52px;\n"
"    font-weight: bold;\n"
"    letter-spacing: 6px;\n"
"}\n"
"\n"
"QLabel#resultLabel[result=\"win\"] {\n"
"    color: #e8c84a;\n"
"}\n"
"\n"
"QLabel#resultLabel[result=\"lose\"] {\n"
"    color: #cc1111;\n"
"}\n"
"\n"
"QLabel#subtitleLabel {\n"
"    color: #888888;\n"
"    font-family: \"Courier New\", monospace;\n"
"    font-size: 12px;\n"
"    letter-spacing: 3px;\n"
"}\n"
"\n"
"QLabel#statsBox {\n"
"    background-color: rgba(30, 0, 0, 180);\n"
"    border: 1px solid #3a0000;\n"
"    border-radius: 4px;\n"
"    color: #bbbbbb;\n"
"    font-family: \"Courier New\", monospace;\n"
"    font-size: 12px;\n"
"    letter-spacing: 1px;\n"
"    padding: 20px;\n"
"}\n"
"\n"
"QPushButton#btnMainMenu {\n"
"    background-color: #cc1111;\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    border-radius: 2px;\n"
"    font-family: \"Courier New\", monospace;\n"
"    font-size: 11px;\n"
"    font-weight: bold;\n"
"    letter-spacing: 4px;\n"
"    padding: 14px 40px;\n"
"    min-width: 180px;\n"
"}\n"
"\n"
"QPushButton#btnMainMenu:hover {\n"
"    background-color: #e81414;\n"
"}\n"
"\n"
"QPushButton#btnMainMenu:pressed {\n"
"    background-color: #991010;\n"
"}\n"
"\n"
"QPushButton#btnPlayAgain {\n"
"    background-color: transparent;\n"
"    color: #888888;\n"
"    border: 1px solid #3a0000;\n"
"    border-radius: 2px;\n"
"    font-family: \"Courier New\", monospace;\n"
"    font-size: 11px;\n"
"    letter-spacing: 4px;\n"
"    padding: 14px 40px;\n"
"    min-width: 180px;\n"
"}\n"
"\n"
"QPushButton#btnPlayAgain:hover {\n"
"    background-color: rgba(60, 0, 0, 120);\n"
"    color: #aaaaaa;\n"
"    border-color: #661111;\n"
"}\n"
"\n"
"QPushButton#btnPlayAgain:pressed {\n"
"    background-color: rgba(30, 0, 0, 160);\n"
"}\n"
"\n"
"QLabel#decorTop {\n"
"    color: #3a0000;\n"
"    font-family: \"Courier New\", monospace;\n"
"    font-size: 10px;\n"
"    letter-spacing: 2px;\n"
"}\n"
"\n"
"QLabel#playerNameLabel {\n"
"    color: #cc8800;\n"
"    font-family: \"Georgia\", serif;\n"
"    font-size: 16px;\n"
"    letter-spacing: 4px;\n"
"}\n"
"   ")
        self.mainLayout = QtWidgets.QVBoxLayout(EndScreen)
        self.mainLayout.setContentsMargins(0, 0, 0, 0)
        self.mainLayout.setSpacing(0)
        self.mainLayout.setObjectName("mainLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.mainLayout.addItem(spacerItem)
        self.titleLabel = QtWidgets.QLabel(parent=EndScreen)
        self.titleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.mainLayout.addWidget(self.titleLabel)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.mainLayout.addItem(spacerItem1)
        self.decorTop = QtWidgets.QLabel(parent=EndScreen)
        self.decorTop.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.decorTop.setObjectName("decorTop")
        self.mainLayout.addWidget(self.decorTop)
        spacerItem2 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.mainLayout.addItem(spacerItem2)
        self.resultLabel = QtWidgets.QLabel(parent=EndScreen)
        self.resultLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.resultLabel.setObjectName("resultLabel")
        self.mainLayout.addWidget(self.resultLabel)
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.mainLayout.addItem(spacerItem3)
        self.playerNameLabel = QtWidgets.QLabel(parent=EndScreen)
        self.playerNameLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.playerNameLabel.setObjectName("playerNameLabel")
        self.mainLayout.addWidget(self.playerNameLabel)
        spacerItem4 = QtWidgets.QSpacerItem(20, 8, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.mainLayout.addItem(spacerItem4)
        self.subtitleLabel = QtWidgets.QLabel(parent=EndScreen)
        self.subtitleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.subtitleLabel.setObjectName("subtitleLabel")
        self.mainLayout.addWidget(self.subtitleLabel)
        spacerItem5 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.mainLayout.addItem(spacerItem5)
        spacerItem6 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.mainLayout.addItem(spacerItem6)

        self.retranslateUi(EndScreen)
        QtCore.QMetaObject.connectSlotsByName(EndScreen)

    def retranslateUi(self, EndScreen):
        _translate = QtCore.QCoreApplication.translate
        EndScreen.setWindowTitle(_translate("EndScreen", "Risk - Oyun Sonu"))
        self.titleLabel.setText(_translate("EndScreen", "R I S K"))
        self.decorTop.setText(_translate("EndScreen", "─────────────────────────────────────────────────"))
        self.resultLabel.setText(_translate("EndScreen", "KAZANDINIZ"))
        self.playerNameLabel.setText(_translate("EndScreen", "KOMUTAN ADI"))
        self.subtitleLabel.setText(_translate("EndScreen", "DÜNYA EGEMENLİĞİ TAMAMLANDI"))
