# Form implementation generated from reading ui file 'client/ui/ui_files/game_window.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_GameWindow(object):
    def setupUi(self, GameWindow):
        GameWindow.setObjectName("GameWindow")
        GameWindow.resize(1280, 800)
        GameWindow.setStyleSheet("\n"
"QMainWindow, QWidget#centralwidget {\n"
"  background-color: #1a0a00;\n"
"}\n"
"QFrame#top_bar {\n"
"  background-color: #2b0d00;\n"
"  border-bottom: 2px solid #8b1a1a;\n"
"}\n"
"QFrame#bottom_bar {\n"
"  background-color: #2b0d00;\n"
"  border-top: 2px solid #8b1a1a;\n"
"}\n"
"QFrame#left_panel {\n"
"  background-color: #1f0800;\n"
"  border: 2px solid #6b1010;\n"
"  border-radius: 6px;\n"
"}\n"
"QFrame#right_panel {\n"
"  background-color: #1f0800;\n"
"  border: 2px solid #6b1010;\n"
"  border-radius: 6px;\n"
"}\n"
"QFrame#map_frame {\n"
"  background-color: #0d0500;\n"
"  border: 2px solid #8b1a1a;\n"
"  border-radius: 4px;\n"
"}\n"
"QLabel#label_game_title {\n"
"  color: #e8c090;\n"
"  font-family: \"Andale Mono\";\n"
"  font-size: 18px;\n"
"  font-weight: bold;\n"
"  letter-spacing: 4px;\n"
"}\n"
"QLabel#label_turn_indicator {\n"
"  color: #ffffff;\n"
"  background-color: #8b1a1a;\n"
"  font-family: \"Andale Mono\";\n"
"  font-size: 10px;\n"
"  font-weight: bold;\n"
"  letter-spacing: 3px;\n"
"  padding: 3px 10px;\n"
"  border-radius: 3px;\n"
"}\n"
"QLabel#label_phase {\n"
"  color: #ccaa66;\n"
"  font-family: \"Andale Mono\";\n"
"  font-size: 11px;\n"
"  letter-spacing: 2px;\n"
"}\n"
"QLabel#label_round_value {\n"
"  color: #e8c090;\n"
"  font-family: \"Andale Mono\";\n"
"  font-size: 18px;\n"
"  font-weight: bold;\n"
"}\n"
"QLabel[role=\"section_header\"] {\n"
"  color: #c0704a;\n"
"  font-family: \"Andale Mono\";\n"
"  font-size: 10px;\n"
"  letter-spacing: 2px;\n"
"}\n"
"QLabel#label_player_name {\n"
"  color: #e8c090;\n"
"  font-family: \"Andale Mono\";\n"
"  font-size: 13px;\n"
"  font-weight: bold;\n"
"}\n"
"QLabel#label_player_icon {\n"
"  color: #ff6644;\n"
"  font-size: 20px;\n"
"}\n"
"QLabel#label_troops_value {\n"
"  color: #ff6644;\n"
"  font-family: \"Andale Mono\";\n"
"  font-size: 32px;\n"
"  font-weight: bold;\n"
"}\n"
"QLabel#label_territories_value {\n"
"  color: #ff9944;\n"
"  font-family: \"Andale Mono\";\n"
"  font-size: 22px;\n"
"  font-weight: bold;\n"
"}\n"
"QLabel#label_cards_value {\n"
"  color: #ffcc44;\n"
"  font-family: \"Andale Mono\";\n"
"  font-size: 22px;\n"
"  font-weight: bold;\n"
"}\n"
"QLabel#label_continents_value {\n"
"  color: #88cc44;\n"
"  font-family: \"Andale Mono\";\n"
"  font-size: 11px;\n"
"}\n"
"QLabel#label_opponent_name {\n"
"  color: #8090b0;\n"
"  font-family: \"Andale Mono\";\n"
"  font-size: 13px;\n"
"  font-weight: bold;\n"
"}\n"
"QLabel#label_opponent_icon {\n"
"  color: #4488cc;\n"
"  font-size: 20px;\n"
"}\n"
"QLabel#label_opponent_troops_value {\n"
"  color: #4488cc;\n"
"  font-family: \"Andale Mono\";\n"
"  font-size: 32px;\n"
"  font-weight: bold;\n"
"}\n"
"QLabel#label_opponent_territories_value {\n"
"  color: #5599dd;\n"
"  font-family: \"Andale Mono\";\n"
"  font-size: 22px;\n"
"  font-weight: bold;\n"
"}\n"
"QLabel#label_map_placeholder {\n"
"  color: #3a1a0a;\n"
"  font-family: \"Andale Mono\";\n"
"  font-size: 12px;\n"
"}\n"
"QProgressBar#progress_bar {\n"
"  background-color: #0d0500;\n"
"  border: 1px solid #4a1a0a;\n"
"  border-radius: 3px;\n"
"  color: #e8c090;\n"
"  font-family: \"Andale Mono\";\n"
"  font-size: 9px;\n"
"  text-align: center;\n"
"}\n"
"QProgressBar#progress_bar::chunk {\n"
"  background-color: qlineargradient(x1:0,y1:0,x2:1,y2:0,stop:0 #8b1a1a,stop:1 #cc3300);\n"
"  border-radius: 2px;\n"
"}\n"
"QTextEdit#log_box {\n"
"  background-color: #0d0500;\n"
"  color: #aa8866;\n"
"  font-family: \"Andale Mono\";\n"
"  font-size: 10px;\n"
"  border: 1px solid #4a1a0a;\n"
"  border-radius: 3px;\n"
"}\n"
"QPushButton#btn_reinforce {\n"
"  background-color: #3a1500;\n"
"  color: #ffcc88;\n"
"  font-family: \"Andale Mono\";\n"
"  font-size: 11px;\n"
"  font-weight: bold;\n"
"  letter-spacing: 2px;\n"
"  border: 1px solid #8b4010;\n"
"  border-radius: 4px;\n"
"  padding: 6px 4px;\n"
"}\n"
"QPushButton#btn_reinforce:hover { background-color: #5a2500; border-color: #cc6010; }\n"
"QPushButton#btn_attack {\n"
"  background-color: #3a0a0a;\n"
"  color: #ff8888;\n"
"  font-family: \"Andale Mono\";\n"
"  font-size: 11px;\n"
"  font-weight: bold;\n"
"  letter-spacing: 2px;\n"
"  border: 1px solid #8b1010;\n"
"  border-radius: 4px;\n"
"  padding: 6px 4px;\n"
"}\n"
"QPushButton#btn_attack:hover { background-color: #5a1010; border-color: #cc2020; }\n"
"QPushButton#btn_fortify {\n"
"  background-color: #0a1a3a;\n"
"  color: #88aaff;\n"
"  font-family: \"Andale Mono\";\n"
"  font-size: 11px;\n"
"  font-weight: bold;\n"
"  letter-spacing: 2px;\n"
"  border: 1px solid #102060;\n"
"  border-radius: 4px;\n"
"  padding: 6px 4px;\n"
"}\n"
"QPushButton#btn_fortify:hover { background-color: #102a5a; border-color: #2040cc; }\n"
"QPushButton#btn_end_turn {\n"
"  background-color: #1a1a0a;\n"
"  color: #cccc44;\n"
"  font-family: \"Andale Mono\";\n"
"  font-size: 11px;\n"
"  font-weight: bold;\n"
"  letter-spacing: 2px;\n"
"  border: 2px solid #888810;\n"
"  border-radius: 4px;\n"
"  padding: 8px 4px;\n"
"}\n"
"QPushButton#btn_end_turn:hover { background-color: #2a2a10; border-color: #cccc20; }\n"
"QPushButton#btn_cards {\n"
"  background-color: #1a0a3a;\n"
"  color: #cc88ff;\n"
"  font-family: \"Andale Mono\";\n"
"  font-size: 10px;\n"
"  letter-spacing: 1px;\n"
"  border: 1px solid #441060;\n"
"  border-radius: 4px;\n"
"  padding: 4px;\n"
"}\n"
"QLabel#label_status_conn {\n"
"  color: #44cc44;\n"
"  font-family: \"Andale Mono\";\n"
"  font-size: 10px;\n"
"}\n"
"QLabel#label_status_server {\n"
"  color: #888888;\n"
"  font-family: \"Andale Mono\";\n"
"  font-size: 10px;\n"
"}\n"
"QLabel#label_status_hint {\n"
"  color: #aa7744;\n"
"  font-family: \"Andale Mono\";\n"
"  font-size: 10px;\n"
"  font-style: italic;\n"
"}\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(parent=GameWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.main_vbox = QtWidgets.QVBoxLayout(self.centralwidget)
        self.main_vbox.setContentsMargins(0, 0, 0, 0)
        self.main_vbox.setSpacing(0)
        self.main_vbox.setObjectName("main_vbox")
        self.top_bar = QtWidgets.QFrame(parent=self.centralwidget)
        self.top_bar.setMinimumHeight(50)
        self.top_bar.setMaximumHeight(50)
        self.top_bar.setObjectName("top_bar")
        self.top_bar_hbox = QtWidgets.QHBoxLayout(self.top_bar)
        self.top_bar_hbox.setContentsMargins(12, 4, 12, 4)
        self.top_bar_hbox.setSpacing(10)
        self.top_bar_hbox.setObjectName("top_bar_hbox")
        self.label_game_title = QtWidgets.QLabel(parent=self.top_bar)
        self.label_game_title.setObjectName("label_game_title")
        self.top_bar_hbox.addWidget(self.label_game_title)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.top_bar_hbox.addItem(spacerItem)
        self.label_turn_indicator = QtWidgets.QLabel(parent=self.top_bar)
        self.label_turn_indicator.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_turn_indicator.setObjectName("label_turn_indicator")
        self.top_bar_hbox.addWidget(self.label_turn_indicator)
        self.label_phase = QtWidgets.QLabel(parent=self.top_bar)
        self.label_phase.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_phase.setObjectName("label_phase")
        self.top_bar_hbox.addWidget(self.label_phase)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.top_bar_hbox.addItem(spacerItem1)
        self.label_round_header = QtWidgets.QLabel(parent=self.top_bar)
        self.label_round_header.setObjectName("label_round_header")
        self.top_bar_hbox.addWidget(self.label_round_header)
        self.label_round_value = QtWidgets.QLabel(parent=self.top_bar)
        self.label_round_value.setObjectName("label_round_value")
        self.top_bar_hbox.addWidget(self.label_round_value)
        self.main_vbox.addWidget(self.top_bar)
        self.middle_hbox = QtWidgets.QHBoxLayout()
        self.middle_hbox.setContentsMargins(6, 6, 6, 6)
        self.middle_hbox.setSpacing(6)
        self.middle_hbox.setObjectName("middle_hbox")
        self.left_panel = QtWidgets.QFrame(parent=self.centralwidget)
        self.left_panel.setMinimumWidth(200)
        self.left_panel.setMaximumWidth(220)
        self.left_panel.setObjectName("left_panel")
        self.left_vbox = QtWidgets.QVBoxLayout(self.left_panel)
        self.left_vbox.setContentsMargins(10, 10, 10, 10)
        self.left_vbox.setSpacing(8)
        self.left_vbox.setObjectName("left_vbox")
        self.player_header_hbox = QtWidgets.QHBoxLayout()
        self.player_header_hbox.setSpacing(6)
        self.player_header_hbox.setObjectName("player_header_hbox")
        self.label_player_icon = QtWidgets.QLabel(parent=self.left_panel)
        self.label_player_icon.setObjectName("label_player_icon")
        self.player_header_hbox.addWidget(self.label_player_icon)
        self.label_player_name = QtWidgets.QLabel(parent=self.left_panel)
        self.label_player_name.setObjectName("label_player_name")
        self.player_header_hbox.addWidget(self.label_player_name)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.player_header_hbox.addItem(spacerItem2)
        self.left_vbox.addLayout(self.player_header_hbox)
        self.div1 = QtWidgets.QFrame(parent=self.left_panel)
        self.div1.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.div1.setObjectName("div1")
        self.left_vbox.addWidget(self.div1)
        self.label_troops_header = QtWidgets.QLabel(parent=self.left_panel)
        self.label_troops_header.setObjectName("label_troops_header")
        self.left_vbox.addWidget(self.label_troops_header)
        self.label_troops_value = QtWidgets.QLabel(parent=self.left_panel)
        self.label_troops_value.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_troops_value.setObjectName("label_troops_value")
        self.left_vbox.addWidget(self.label_troops_value)
        self.div2 = QtWidgets.QFrame(parent=self.left_panel)
        self.div2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.div2.setObjectName("div2")
        self.left_vbox.addWidget(self.div2)
        self.label_territories_header = QtWidgets.QLabel(parent=self.left_panel)
        self.label_territories_header.setObjectName("label_territories_header")
        self.left_vbox.addWidget(self.label_territories_header)
        self.label_territories_value = QtWidgets.QLabel(parent=self.left_panel)
        self.label_territories_value.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_territories_value.setObjectName("label_territories_value")
        self.left_vbox.addWidget(self.label_territories_value)
        self.progress_bar = QtWidgets.QProgressBar(parent=self.left_panel)
        self.progress_bar.setProperty("value", 33)
        self.progress_bar.setTextVisible(False)
        self.progress_bar.setObjectName("progress_bar")
        self.left_vbox.addWidget(self.progress_bar)
        self.div3 = QtWidgets.QFrame(parent=self.left_panel)
        self.div3.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.div3.setObjectName("div3")
        self.left_vbox.addWidget(self.div3)
        self.label_continents_header = QtWidgets.QLabel(parent=self.left_panel)
        self.label_continents_header.setObjectName("label_continents_header")
        self.left_vbox.addWidget(self.label_continents_header)
        self.label_continents_value = QtWidgets.QLabel(parent=self.left_panel)
        self.label_continents_value.setObjectName("label_continents_value")
        self.left_vbox.addWidget(self.label_continents_value)
        self.div4 = QtWidgets.QFrame(parent=self.left_panel)
        self.div4.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.div4.setObjectName("div4")
        self.left_vbox.addWidget(self.div4)
        self.label_cards_header = QtWidgets.QLabel(parent=self.left_panel)
        self.label_cards_header.setObjectName("label_cards_header")
        self.left_vbox.addWidget(self.label_cards_header)
        self.label_cards_value = QtWidgets.QLabel(parent=self.left_panel)
        self.label_cards_value.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_cards_value.setObjectName("label_cards_value")
        self.left_vbox.addWidget(self.label_cards_value)
        self.btn_cards = QtWidgets.QPushButton(parent=self.left_panel)
        self.btn_cards.setObjectName("btn_cards")
        self.left_vbox.addWidget(self.btn_cards)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.left_vbox.addItem(spacerItem3)
        self.middle_hbox.addWidget(self.left_panel)
        self.map_frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.map_frame.setObjectName("map_frame")
        self.map_vbox = QtWidgets.QVBoxLayout(self.map_frame)
        self.map_vbox.setContentsMargins(0, 0, 0, 0)
        self.map_vbox.setSpacing(0)
        self.map_vbox.setObjectName("map_vbox")
        self.label_map_placeholder = QtWidgets.QLabel(parent=self.map_frame)
        self.label_map_placeholder.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_map_placeholder.setObjectName("label_map_placeholder")
        self.map_vbox.addWidget(self.label_map_placeholder)
        self.middle_hbox.addWidget(self.map_frame)
        self.right_panel = QtWidgets.QFrame(parent=self.centralwidget)
        self.right_panel.setMinimumWidth(200)
        self.right_panel.setMaximumWidth(220)
        self.right_panel.setObjectName("right_panel")
        self.right_vbox = QtWidgets.QVBoxLayout(self.right_panel)
        self.right_vbox.setContentsMargins(10, 10, 10, 10)
        self.right_vbox.setSpacing(8)
        self.right_vbox.setObjectName("right_vbox")
        self.opponent_header_hbox = QtWidgets.QHBoxLayout()
        self.opponent_header_hbox.setSpacing(6)
        self.opponent_header_hbox.setObjectName("opponent_header_hbox")
        self.label_opponent_icon = QtWidgets.QLabel(parent=self.right_panel)
        self.label_opponent_icon.setObjectName("label_opponent_icon")
        self.opponent_header_hbox.addWidget(self.label_opponent_icon)
        self.label_opponent_name = QtWidgets.QLabel(parent=self.right_panel)
        self.label_opponent_name.setObjectName("label_opponent_name")
        self.opponent_header_hbox.addWidget(self.label_opponent_name)
        spacerItem4 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.opponent_header_hbox.addItem(spacerItem4)
        self.right_vbox.addLayout(self.opponent_header_hbox)
        self.div5 = QtWidgets.QFrame(parent=self.right_panel)
        self.div5.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.div5.setObjectName("div5")
        self.right_vbox.addWidget(self.div5)
        self.label_opp_troops_header = QtWidgets.QLabel(parent=self.right_panel)
        self.label_opp_troops_header.setObjectName("label_opp_troops_header")
        self.right_vbox.addWidget(self.label_opp_troops_header)
        self.label_opponent_troops_value = QtWidgets.QLabel(parent=self.right_panel)
        self.label_opponent_troops_value.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_opponent_troops_value.setObjectName("label_opponent_troops_value")
        self.right_vbox.addWidget(self.label_opponent_troops_value)
        self.div6 = QtWidgets.QFrame(parent=self.right_panel)
        self.div6.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.div6.setObjectName("div6")
        self.right_vbox.addWidget(self.div6)
        self.label_opp_territories_header = QtWidgets.QLabel(parent=self.right_panel)
        self.label_opp_territories_header.setObjectName("label_opp_territories_header")
        self.right_vbox.addWidget(self.label_opp_territories_header)
        self.label_opponent_territories_value = QtWidgets.QLabel(parent=self.right_panel)
        self.label_opponent_territories_value.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_opponent_territories_value.setObjectName("label_opponent_territories_value")
        self.right_vbox.addWidget(self.label_opponent_territories_value)
        self.div7 = QtWidgets.QFrame(parent=self.right_panel)
        self.div7.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.div7.setObjectName("div7")
        self.right_vbox.addWidget(self.div7)
        self.label_actions_header = QtWidgets.QLabel(parent=self.right_panel)
        self.label_actions_header.setObjectName("label_actions_header")
        self.right_vbox.addWidget(self.label_actions_header)
        self.btn_reinforce = QtWidgets.QPushButton(parent=self.right_panel)
        self.btn_reinforce.setMinimumHeight(36)
        self.btn_reinforce.setObjectName("btn_reinforce")
        self.right_vbox.addWidget(self.btn_reinforce)
        self.btn_attack = QtWidgets.QPushButton(parent=self.right_panel)
        self.btn_attack.setMinimumHeight(36)
        self.btn_attack.setObjectName("btn_attack")
        self.right_vbox.addWidget(self.btn_attack)
        self.btn_fortify = QtWidgets.QPushButton(parent=self.right_panel)
        self.btn_fortify.setMinimumHeight(36)
        self.btn_fortify.setObjectName("btn_fortify")
        self.right_vbox.addWidget(self.btn_fortify)
        self.div8 = QtWidgets.QFrame(parent=self.right_panel)
        self.div8.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.div8.setObjectName("div8")
        self.right_vbox.addWidget(self.div8)
        self.label_log_header = QtWidgets.QLabel(parent=self.right_panel)
        self.label_log_header.setObjectName("label_log_header")
        self.right_vbox.addWidget(self.label_log_header)
        self.log_box = QtWidgets.QTextEdit(parent=self.right_panel)
        self.log_box.setReadOnly(True)
        self.log_box.setMinimumHeight(120)
        self.log_box.setObjectName("log_box")
        self.right_vbox.addWidget(self.log_box)
        spacerItem5 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.right_vbox.addItem(spacerItem5)
        self.btn_end_turn = QtWidgets.QPushButton(parent=self.right_panel)
        self.btn_end_turn.setMinimumHeight(44)
        self.btn_end_turn.setObjectName("btn_end_turn")
        self.right_vbox.addWidget(self.btn_end_turn)
        self.middle_hbox.addWidget(self.right_panel)
        self.main_vbox.addLayout(self.middle_hbox)
        self.bottom_bar = QtWidgets.QFrame(parent=self.centralwidget)
        self.bottom_bar.setMinimumHeight(30)
        self.bottom_bar.setMaximumHeight(30)
        self.bottom_bar.setObjectName("bottom_bar")
        self.bottom_hbox = QtWidgets.QHBoxLayout(self.bottom_bar)
        self.bottom_hbox.setContentsMargins(12, 2, 12, 2)
        self.bottom_hbox.setSpacing(16)
        self.bottom_hbox.setObjectName("bottom_hbox")
        self.label_status_conn = QtWidgets.QLabel(parent=self.bottom_bar)
        self.label_status_conn.setObjectName("label_status_conn")
        self.bottom_hbox.addWidget(self.label_status_conn)
        self.label_status_server = QtWidgets.QLabel(parent=self.bottom_bar)
        self.label_status_server.setObjectName("label_status_server")
        self.bottom_hbox.addWidget(self.label_status_server)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.bottom_hbox.addItem(spacerItem6)
        self.label_status_hint = QtWidgets.QLabel(parent=self.bottom_bar)
        self.label_status_hint.setObjectName("label_status_hint")
        self.bottom_hbox.addWidget(self.label_status_hint)
        self.main_vbox.addWidget(self.bottom_bar)
        GameWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(GameWindow)

    def retranslateUi(self, GameWindow):
        _translate = QtCore.QCoreApplication.translate
        GameWindow.setWindowTitle(_translate("GameWindow", "RISK"))
        self.label_game_title.setText(_translate("GameWindow", "R I S K"))
        self.label_turn_indicator.setText(_translate("GameWindow", "SENİN TURUN"))
        self.label_phase.setText(_translate("GameWindow", "FAZ: TAKVİYE"))
        self.label_round_header.setText(_translate("GameWindow", "TUR"))
        self.label_round_header.setStyleSheet(_translate("GameWindow", "color:#c0704a; font-family:\"Andale Mono\"; font-size:10px; letter-spacing:2px;"))
        self.label_round_value.setText(_translate("GameWindow", "1"))
        self.label_player_icon.setText(_translate("GameWindow", "⚔"))
        self.label_player_name.setText(_translate("GameWindow", "OYUNCU 1"))
        self.div1.setStyleSheet(_translate("GameWindow", "background-color:#4a1a0a;"))
        self.label_troops_header.setText(_translate("GameWindow", "KALAN ASKER"))
        self.label_troops_header.setStyleSheet(_translate("GameWindow", "color:#c0704a; font-family:\"Andale Mono\"; font-size:10px; letter-spacing:2px;"))
        self.label_troops_value.setText(_translate("GameWindow", "12"))
        self.div2.setStyleSheet(_translate("GameWindow", "background-color:#4a1a0a;"))
        self.label_territories_header.setText(_translate("GameWindow", "BÖLGELER"))
        self.label_territories_header.setStyleSheet(_translate("GameWindow", "color:#c0704a; font-family:\"Andale Mono\"; font-size:10px; letter-spacing:2px;"))
        self.label_territories_value.setText(_translate("GameWindow", "14 / 42"))
        self.div3.setStyleSheet(_translate("GameWindow", "background-color:#4a1a0a;"))
        self.label_continents_header.setText(_translate("GameWindow", "KONTROL EDİLEN KITALAR"))
        self.label_continents_header.setStyleSheet(_translate("GameWindow", "color:#c0704a; font-family:\"Andale Mono\"; font-size:10px; letter-spacing:2px;"))
        self.label_continents_value.setText(_translate("GameWindow", "—"))
        self.div4.setStyleSheet(_translate("GameWindow", "background-color:#4a1a0a;"))
        self.label_cards_header.setText(_translate("GameWindow", "ELİMDEKİ KARTLAR"))
        self.label_cards_header.setStyleSheet(_translate("GameWindow", "color:#c0704a; font-family:\"Andale Mono\"; font-size:10px; letter-spacing:2px;"))
        self.label_cards_value.setText(_translate("GameWindow", "0"))
        self.btn_cards.setText(_translate("GameWindow", "KARTLARI GÖSTER"))
        self.label_map_placeholder.setText(_translate("GameWindow", "[ SVG HARİTA — Python tarafında QSvgWidget ile yükle ]"))
        self.label_opponent_icon.setText(_translate("GameWindow", "🛡"))
        self.label_opponent_name.setText(_translate("GameWindow", "RAKİP BEKLENİYOR"))
        self.div5.setStyleSheet(_translate("GameWindow", "background-color:#4a1a0a;"))
        self.label_opp_troops_header.setText(_translate("GameWindow", "RAKİP ASKERİ"))
        self.label_opp_troops_header.setStyleSheet(_translate("GameWindow", "color:#c0704a; font-family:\"Andale Mono\"; font-size:10px; letter-spacing:2px;"))
        self.label_opponent_troops_value.setText(_translate("GameWindow", "?"))
        self.div6.setStyleSheet(_translate("GameWindow", "background-color:#4a1a0a;"))
        self.label_opp_territories_header.setText(_translate("GameWindow", "RAKİP BÖLGELERİ"))
        self.label_opp_territories_header.setStyleSheet(_translate("GameWindow", "color:#c0704a; font-family:\"Andale Mono\"; font-size:10px; letter-spacing:2px;"))
        self.label_opponent_territories_value.setText(_translate("GameWindow", "? / 42"))
        self.div7.setStyleSheet(_translate("GameWindow", "background-color:#4a1a0a;"))
        self.label_actions_header.setText(_translate("GameWindow", "AKSİYONLAR"))
        self.label_actions_header.setStyleSheet(_translate("GameWindow", "color:#c0704a; font-family:\"Andale Mono\"; font-size:10px; letter-spacing:2px;"))
        self.btn_reinforce.setText(_translate("GameWindow", "TAKVİYE GÖNDER"))
        self.btn_attack.setText(_translate("GameWindow", "SALDIRI BAŞLAT"))
        self.btn_fortify.setText(_translate("GameWindow", "KUVVETLERİ TAŞI"))
        self.div8.setStyleSheet(_translate("GameWindow", "background-color:#4a1a0a;"))
        self.label_log_header.setText(_translate("GameWindow", "OYUN LOGU"))
        self.label_log_header.setStyleSheet(_translate("GameWindow", "color:#c0704a; font-family:\"Andale Mono\"; font-size:10px; letter-spacing:2px;"))
        self.btn_end_turn.setText(_translate("GameWindow", "TURU BİTİR ▶"))
        self.label_status_conn.setText(_translate("GameWindow", "● BAĞLI"))
        self.label_status_server.setText(_translate("GameWindow", "SUNUCU: —"))
        self.label_status_hint.setText(_translate("GameWindow", "Bölge seçmek için haritaya tıkla"))
