# Form implementation generated from reading ui file 'client/ui/ui_files/occupy_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_OccupyDialog(object):
    def setupUi(self, OccupyDialog):
        OccupyDialog.setObjectName("OccupyDialog")
        OccupyDialog.resize(350, 150)
        self.verticalLayout = QtWidgets.QVBoxLayout(OccupyDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.infoLabel = QtWidgets.QLabel(parent=OccupyDialog)
        self.infoLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.infoLabel.setObjectName("infoLabel")
        self.verticalLayout.addWidget(self.infoLabel)
        self.sliderLayout = QtWidgets.QHBoxLayout()
        self.sliderLayout.setObjectName("sliderLayout")
        self.slider = QtWidgets.QSlider(parent=OccupyDialog)
        self.slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.slider.setObjectName("slider")
        self.sliderLayout.addWidget(self.slider)
        self.spinBox = QtWidgets.QSpinBox(parent=OccupyDialog)
        self.spinBox.setObjectName("spinBox")
        self.sliderLayout.addWidget(self.spinBox)
        self.verticalLayout.addLayout(self.sliderLayout)
        self.btnConfirm = QtWidgets.QPushButton(parent=OccupyDialog)
        self.btnConfirm.setObjectName("btnConfirm")
        self.verticalLayout.addWidget(self.btnConfirm)

        self.retranslateUi(OccupyDialog)
        QtCore.QMetaObject.connectSlotsByName(OccupyDialog)

    def retranslateUi(self, OccupyDialog):
        _translate = QtCore.QCoreApplication.translate
        OccupyDialog.setWindowTitle(_translate("OccupyDialog", "Bölge Fethedildi! Askerleri Kaydır"))
        self.infoLabel.setText(_translate("OccupyDialog", "Tebrikler Komutan!\n"
"Bölgeyi fethettiniz.\n"
"Kaç asker aktarmak istersiniz?"))
        self.btnConfirm.setStyleSheet(_translate("OccupyDialog", "background-color: #44cc44; color: white; font-weight: bold; padding: 5px;"))
        self.btnConfirm.setText(_translate("OccupyDialog", "Birlikleri Kaydır"))
