# Form implementation generated from reading ui file 'client/ui/ui_files/troop_selection_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TroopSelectionDialog(object):
    def setupUi(self, TroopSelectionDialog):
        TroopSelectionDialog.setObjectName("TroopSelectionDialog")
        TroopSelectionDialog.setMinimumWidth(320)
        self.layout = QtWidgets.QVBoxLayout(TroopSelectionDialog)
        self.layout.setObjectName("layout")
        self.info_label = QtWidgets.QLabel(parent=TroopSelectionDialog)
        self.info_label.setObjectName("info_label")
        self.layout.addWidget(self.info_label)
        self.control_layout = QtWidgets.QHBoxLayout()
        self.control_layout.setObjectName("control_layout")
        self.slider = QtWidgets.QSlider(parent=TroopSelectionDialog)
        self.slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.slider.setMinimum(1)
        self.slider.setMaximum(100)
        self.slider.setProperty("value", 1)
        self.slider.setObjectName("slider")
        self.control_layout.addWidget(self.slider)
        self.spinbox = QtWidgets.QSpinBox(parent=TroopSelectionDialog)
        self.spinbox.setMinimum(1)
        self.spinbox.setMaximum(100)
        self.spinbox.setProperty("value", 1)
        self.spinbox.setObjectName("spinbox")
        self.control_layout.addWidget(self.spinbox)
        self.layout.addLayout(self.control_layout)
        self.button_layout = QtWidgets.QHBoxLayout()
        self.button_layout.setObjectName("button_layout")
        self.btn_ok = QtWidgets.QPushButton(parent=TroopSelectionDialog)
        self.btn_ok.setObjectName("btn_ok")
        self.button_layout.addWidget(self.btn_ok)
        self.btn_cancel = QtWidgets.QPushButton(parent=TroopSelectionDialog)
        self.btn_cancel.setObjectName("btn_cancel")
        self.button_layout.addWidget(self.btn_cancel)
        self.layout.addLayout(self.button_layout)

        self.retranslateUi(TroopSelectionDialog)
        self.slider.valueChanged['int'].connect(self.spinbox.setValue) # type: ignore
        self.spinbox.valueChanged['int'].connect(self.slider.setValue) # type: ignore
        self.btn_ok.clicked.connect(TroopSelectionDialog.accept) # type: ignore
        self.btn_cancel.clicked.connect(TroopSelectionDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(TroopSelectionDialog)

    def retranslateUi(self, TroopSelectionDialog):
        _translate = QtCore.QCoreApplication.translate
        TroopSelectionDialog.setWindowTitle(_translate("TroopSelectionDialog", "Takviye Gönder"))
        TroopSelectionDialog.setStyleSheet(_translate("TroopSelectionDialog", "background-color: #1f0800; color: #e8c090; font-family: \'Andale Mono\';"))
        self.info_label.setText(_translate("TroopSelectionDialog", "Bölgeye takviye edilecek\n"
"asker miktarını seçin:"))
        self.slider.setStyleSheet(_translate("TroopSelectionDialog", "QSlider::handle:horizontal { background: #8b1a1a; width: 15px; border-radius: 3px; }"))
        self.spinbox.setStyleSheet(_translate("TroopSelectionDialog", "background-color: #0d0500; color: #ff6644; font-size: 14px; font-weight: bold; border: 1px solid #4a1a0a;"))
        self.btn_ok.setText(_translate("TroopSelectionDialog", "ONAYLA"))
        self.btn_ok.setStyleSheet(_translate("TroopSelectionDialog", "background-color: #3a1500; color: #ffcc88; font-weight: bold; padding: 6px; border: 1px solid #8b4010; border-radius: 4px;"))
        self.btn_cancel.setText(_translate("TroopSelectionDialog", "İPTAL"))
        self.btn_cancel.setStyleSheet(_translate("TroopSelectionDialog", "background-color: #1a1a0a; color: #888888; padding: 6px; border: 1px solid #4a1a0a; border-radius: 4px;"))
